version: '3.8'

services:

  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rides
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rides:
    image: rides
    build:
      context: ./services/rides
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ../images:/images
      - m2-repo:/root/.m2
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:5432/rides"

volumes:
  m2-repo:
  postgres:
    driver: local
